Repository StreamingGate/Playground, pull requests merged in 2022-02, with the labels that each got.

#114 fix : infinite-scroll change param index -> last pk
  src/server/main-service/src/main/java/com/example/mainservice/controller/MainController.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/LiveRoom/LiveRoomRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/VideoRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/service/MainService.java
  src/server/main-service/src/main/resources/application.yml
Labels: fix

#120 fix : add uuid field to friend list
  src/server/main-service/src/main/java/com/example/mainservice/dto/FriendDto.java
  src/server/main-service/src/main/resources/application.yml
Labels: fix

#115 desgn, feat : category chip toggle button in Main page
  src/frontend/src/assets/icons/AddFullCircle.svg
  src/frontend/src/assets/icons/ArrowLeft.svg
  src/frontend/src/assets/icons/ArrowRight.svg
  src/frontend/src/assets/icons/LiveStreaming.svg
  src/frontend/src/assets/icons/Logout.svg
  src/frontend/src/components/buttons/ChipButton/ChipButton.jsx
  src/frontend/src/components/buttons/ChipButton/ChipButton.stories.jsx
  src/frontend/src/components/buttons/ChipButton/ChipButton.style.js
  src/frontend/src/components/buttons/IconButton/IconButton.jsx
  src/frontend/src/components/buttons/index.js
  src/frontend/src/components/cores/Icons/AddFullCircle.jsx
  src/frontend/src/components/cores/Icons/ArrowLeft.jsx
  src/frontend/src/components/cores/Icons/ArrowRight.jsx
  src/frontend/src/components/cores/Icons/LiveStreaming.jsx
  src/frontend/src/components/cores/Icons/Logout.jsx
  src/frontend/src/components/cores/index.js
  src/frontend/src/components/dataDisplays/Avatar/Avatar.jsx
  src/frontend/src/components/feedbacks/BackDrop/BackDrop.jsx
  src/frontend/src/components/feedbacks/BackDrop/BackDrop.style.js
  src/frontend/src/components/layouts/Header/BaseHeader.jsx
  src/frontend/src/components/layouts/Header/Header.jsx
  src/frontend/src/components/layouts/Header/Header.stories.jsx
  src/frontend/src/components/layouts/Header/Header.style.js
  src/frontend/src/components/layouts/Header/SearchBar.jsx
  src/frontend/src/components/layouts/Header/SearchForm.jsx
  src/frontend/src/components/layouts/MainLayout/MainLayout.jsx
  src/frontend/src/components/layouts/MainLayout/MainLayout.style.js
  src/frontend/src/components/layouts/SideFriendList/FriendItem.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.stories.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.style.js
  src/frontend/src/components/layouts/VideoGrid/VideoGrid.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.style.js
  src/frontend/src/pages/Home/CategorySlider/CategorySlider.jsx
  src/frontend/src/pages/Home/CategorySlider/CategorySlider.style.js
  src/frontend/src/pages/Home/HomePage/HomePage.jsx
  src/frontend/src/pages/Home/HomePage/HomePage.stories.jsx
  src/frontend/src/pages/Home/HomePage/HomePage.sytle.js
  src/frontend/src/pages/VideoPlay/ChatRoom/ChatRoom.style.js
  src/frontend/src/storybookDocs/color.stories.mdx
  src/frontend/src/utils/constant/theme.constants.js
Labels: feat, design

#118 feat : add pstTime to chat subscriber
  src/server/chat-service/build.gradle
  src/server/chat-service/src/main/java/com/example/chatservice/config/RedisConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/Chat.java
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
Labels: feat

#135 fix : JWT decoder fail fix
  src/server/api-gateway/build.gradle
  src/server/api-gateway/src/main/java/com/example/apigateway/filter/AuthenticationFilter.java
  src/server/api-gateway/src/main/resources/application.yml
  src/server/user-service/src/main/java/com/example/userservice/config/security/AuthenticationFilter.java
  src/server/user-service/src/main/resources/application.yml
Labels: fix

#130 design : remove corner radius before saving profile image
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/NickNameInputViewController.swift
Labels: design

#136 fix : fixed `/list` orderBy not working
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/VideoRepository.java
Labels: fix

#138 feat : connect main-service api under /friend and /notification
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Network/ErrorCodeConverter.swift
  src/ios/PlayGround/PlayGround/Network/MainService/MainDataModel.swift
  src/ios/PlayGround/PlayGround/Network/MainService/MainServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/NetworkResultManager.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/CustomTabViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/CreateTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/HomeTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MyTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/String+getDateString.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/Friend.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendPopUpViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/ViewModel/FriendViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewModel/HomeViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/FriendRequestCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/FriendRequestViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/Notice.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/NoticeCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/NoticeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/NoticeViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPage.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayExplainViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: feat, design

#140 refactor : improve bottom tab structure
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/CustomTabViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/Tab.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/HomeTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MainCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MyTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/MyPageViewController.swift
Labels: refactor

#143 feat : apply notification message
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UILabel+PartOfTextColorChange.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/Notice.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/NoticeCell.swift
Labels: feat

#144 feat : connect with main-service friend
  src/frontend/src/components/feedbacks/Modals/AcceptFriendModal/AcceptFriendModal.jsx
  src/frontend/src/components/feedbacks/Modals/DeleteFriendModal/DeleteFriendModal.jsx
  src/frontend/src/components/layouts/Header/BaseHeader.jsx
  src/frontend/src/components/layouts/Header/Dropdowns/AlarmDropdown.jsx
  src/frontend/src/components/layouts/Header/Dropdowns/Dropdown.style.js
  src/frontend/src/components/layouts/Header/Dropdowns/ProfileDropdown.jsx
  src/frontend/src/components/layouts/Header/Header.style.js
  src/frontend/src/pages/Home/HomePage/HomePage.jsx
  src/frontend/src/pages/VideoPlay/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useDeleteFriend.js
  src/frontend/src/utils/hook/query/useFriendList.js
  src/frontend/src/utils/hook/query/useGetFriendReqList.js
  src/frontend/src/utils/hook/query/useGetNotiList.js
  src/frontend/src/utils/hook/query/useHandleFriendReq.js
  src/frontend/src/utils/hook/query/useMainVideoList.js
Labels: feat, design

#146 fix : add close logic regarding player
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/CreateTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MyTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: fix

#147 feat : create upload-service , add api-gateway to upload-service
  config/docker-compose.yml
  src/server/api-gateway/src/main/resources/application.yml
  src/server/upload-service/.gitignore
  src/server/upload-service/Dockerfile
  src/server/upload-service/build.gradle
  src/server/upload-service/gradle/wrapper/gradle-wrapper.jar
  src/server/upload-service/gradle/wrapper/gradle-wrapper.properties
  src/server/upload-service/gradlew
  src/server/upload-service/gradlew.bat
  src/server/upload-service/settings.gradle
  src/server/upload-service/src/main/java/com/example/uploadservice/UploadServiceApplication.java
  src/server/upload-service/src/main/java/com/example/uploadservice/config/S3Config.java
  src/server/upload-service/src/main/java/com/example/uploadservice/controller/UploadController.java
  src/server/upload-service/src/main/java/com/example/uploadservice/dto/UploadRequestDto.java
  src/server/upload-service/src/main/java/com/example/uploadservice/dto/VideoDto.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Category.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Metadata/Metadata.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Metadata/MetadataRepository.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Metadata/VideoState.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/User/User.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/User/UserRepository.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/User/UserState.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Video/Video.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Video/VideoRepository.java
  src/server/upload-service/src/main/java/com/example/uploadservice/exceptionHandler/ErrorResponse.java
  src/server/upload-service/src/main/java/com/example/uploadservice/exceptionHandler/ExceptionController.java
  src/server/upload-service/src/main/java/com/example/uploadservice/exceptionHandler/customexception/CustomUploadException.java
  src/server/upload-service/src/main/java/com/example/uploadservice/exceptionHandler/customexception/ErrorCode.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/TranscodeService.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/UploadService.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/VideoService.java
  src/server/upload-service/src/main/resources/application-s3.yml
  src/server/upload-service/src/main/resources/application.yml
  src/server/upload-service/src/test/java/com/example/uploadservice/UploadServiceApplicationTests.java
Labels: feat

#149 design : add video upload page
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_box_grayCircle.imageset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_box_grayCircle.imageset/uploadVideo.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_box_grayCircle.imageset/uploadVideo@2.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_box_grayCircle.imageset/uploadVideo@3.png
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/CreateInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/CreatePopOverViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/CreateTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: design

#161 fix : enable audio play in real device
  src/ios/PlayGround/PlayGround/Presentation/AppDelegate.swift
Labels: fix

#160 feat, design : connect with upload-service api
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Network/MainService/MainServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/UploadService/UploadServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
Labels: feat, design

#163 feat : store userInfo after login and connect MyPage
  src/ios/PlayGround/PlayGround/Network/UserService/UserServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/UserManager.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPage.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountEditViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/MyPageViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
Labels: feat

#158 docs : add error-code.json (in resource/)
  resources/error-code.json
  src/server/room-service/src/main/java/com/example/roomservice/exceptionHandler/customexception/ErrorCode.java
Labels: docs

#162 feat : create video-service api
  config/docker-compose.yml
  src/server/api-gateway/src/main/resources/application.yml
  src/server/video-service/.gitignore
  src/server/video-service/Dockerfile
  src/server/video-service/build.gradle
  src/server/video-service/gradle/wrapper/gradle-wrapper.jar
  src/server/video-service/gradle/wrapper/gradle-wrapper.properties
  src/server/video-service/gradlew
  src/server/video-service/gradlew.bat
  src/server/video-service/settings.gradle
  src/server/video-service/src/main/java/com/example/videoservice/VideoServiceApplication.java
  src/server/video-service/src/main/java/com/example/videoservice/controller/VideoController.java
  src/server/video-service/src/main/java/com/example/videoservice/dto/VideoResponseDto.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Category.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Metadata/Metadata.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Metadata/MetadataRepository.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Metadata/VideoState.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/User/User.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/User/UserRepository.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/User/UserState.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Video/Video.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Video/VideoRepository.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedRepository.java
  src/server/video-service/src/main/java/com/example/videoservice/exceptionHandler/ErrorResponse.java
  src/server/video-service/src/main/java/com/example/videoservice/exceptionHandler/ExceptionController.java
  src/server/video-service/src/main/java/com/example/videoservice/exceptionHandler/customexception/CustomVideoException.java
  src/server/video-service/src/main/java/com/example/videoservice/exceptionHandler/customexception/ErrorCode.java
  src/server/video-service/src/main/java/com/example/videoservice/service/VideoService.java
  src/server/video-service/src/main/resources/application.yml
  src/server/video-service/src/test/java/com/example/videoservice/VideoServiceApplicationTests.java
Labels: feat

#168 feat : increase max-file-size, max-request-size
  src/server/upload-service/src/main/resources/application.yml
Labels: feat

#171 refactor : move video upload process to global thread
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/Progress.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/Upload.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/UploadProgress.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UIViewController+toastMessage.swift
Labels: refactor

#169 feat : add access token in request header and revert to login page if invalid
  src/ios/PlayGround/PlayGround/Network/MainService/MainServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/NetworkResultManager.swift
  src/ios/PlayGround/PlayGround/Network/UploadService/UploadServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/CreateInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/Coordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/CreateTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/HomeTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MainCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UIViewController+SimpleAlert.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/ViewModel/FriendViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewModel/HomeViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/FriendRequestViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/NoticeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/NoticeViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountEditViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewModel.swift
Labels: feat

#173 feat : add history api on user-service
  .gitignore
  src/server/user-service/src/main/java/com/example/userservice/config/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/history/ResponseRoom.java
  src/server/user-service/src/main/java/com/example/userservice/dto/history/ResponseVideo.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/EmailDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/NicknameDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/PwdDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/RegisterUser.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/RequestLogin.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/RequestMyinfo.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/ResponseLogin.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/ResponseUser.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/UserDto.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Metadata/Metadata.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Metadata/MetadataRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Metadata/VideoState.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/Room.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/RoomRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewer.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewerRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/Category.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/User.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Video/Video.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Video/VideoRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedHistory.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedRepository.java
  src/server/user-service/src/main/java/com/example/userservice/service/HistoryService.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
Labels: feat, refactor

#175 feat : add history api on user-service
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/RoomRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/RoomRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewerRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedRepository.java
  src/server/user-service/src/main/java/com/example/userservice/service/HistoryService.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
Labels: refactor

#174 feat : chat-service add profileImage in message, change timezone to utc
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RedisPubSubController.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/Chat.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/ChatConsume.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/ChatProduce.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/room/Room.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisSubscriber.java
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
Labels: feat

#177 fix, feat : add video uuid to home list, create Chat Room after save Video in DB
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoResponseDto.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/VideoService.java
Labels: feat, fix

#182 feat : add mediasoup-ios-client to Xcode project
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Network/Mediasoup/request/Request.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/room/RoomClient.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/room/RoomListener.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/socket/ActionEvent.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/socket/EchoSocket.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/socket/MessageObserver.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/mediasoup-ios-client-Bridging-Header.h
  src/ios/PlayGround/Podfile
  src/ios/PlayGround/Podfile.lock
Labels: feat

#183 feat : add mediasoup-client to project and add consumer
  .gitignore
  config/docker-compose.yml
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.style.js
  src/frontend/src/pages/Studio/MobileStudioPage/MobileStudioPage.jsx
  src/frontend/src/pages/Studio/StudioPage/StudioPage.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/hook/index.js
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useGetVideoInfo.js
  src/frontend/src/utils/hook/useMediaSoupConsume.js
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RedisPubSubController.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/Chat.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/ChatConsume.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/ChatProduce.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/room/Room.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisSubscriber.java
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoResponseDto.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/RoomRepository.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/VideoService.java
  src/server/user-service/src/main/java/com/example/userservice/config/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/history/ResponseRoom.java
  src/server/user-service/src/main/java/com/example/userservice/dto/history/ResponseVideo.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/EmailDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/NicknameDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/PwdDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/RegisterUser.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/RequestLogin.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/RequestMyinfo.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/ResponseLogin.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/ResponseUser.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/UserDto.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Metadata/Metadata.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Metadata/MetadataRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Metadata/VideoState.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/Room.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/RoomRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewer.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewerRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/Category.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/User.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Video/Video.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Video/VideoRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedHistory.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedRepository.java
  src/server/user-service/src/main/java/com/example/userservice/service/HistoryService.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
Labels: feat

#180 fix : create thumbnail as automatic (upload-service)
  src/server/upload-service/src/main/java/com/example/uploadservice/controller/UploadController.java
  src/server/upload-service/src/main/java/com/example/uploadservice/dto/VideoDto.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/TranscodeService.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/UploadService.java
Labels: fix

#186 feat : connect video-service api
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbDown_fill_black.imageset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbDown_fill_black.imageset/thumbDown_fill_black.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbDown_fill_black.imageset/thumbDown_fill_black@2.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbDown_fill_black.imageset/thumbDown_fill_black@3.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbUp_fill_black.imageset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbUp_fill_black.imageset/thumbUp_fill_black.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbUp_fill_black.imageset/thumbUp_fill_black@2.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/thumbUp_fill_black.imageset/thumbUp_fill_black@3.png
  src/ios/PlayGround/PlayGround/Network/MainService/MainDataModel.swift
  src/ios/PlayGround/PlayGround/Network/MainService/MainServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/VideoService/VideoDataModel.swift
  src/ios/PlayGround/PlayGround/Network/VideoService/VideoServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/Chat.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewModel.swift
Labels: feat

#187 feat : add room uuid check api, docker-compose file update
  config/docker-compose.yml
  src/server/room-service/build.gradle
  src/server/room-service/src/main/java/com/example/roomservice/controller/RoomController.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/ResponseDto.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/RoomRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/RoomViewer/RoomViewer.java
  src/server/room-service/src/main/java/com/example/roomservice/service/RoomService.java
Labels: feat

#190 feat : connect with chat-service
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatDataModel.swift
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/String+getDateString.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChatCell.swift
Labels: feat

#191 feat : connect main-service in VideoPlay page
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.style.js
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useVideoAction.js
Labels: feat

#197 feat : add refresh token, fix room-service, fix DB schema
  data/mariadb/schema.sql
  src/server/api-gateway/src/main/java/com/example/apigateway/filter/AuthenticationFilter.java
  src/server/api-gateway/src/main/resources/application.yml
  src/server/main-service/src/main/java/com/example/mainservice/entity/Room/Room.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewer.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/User.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/Video.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedHistory.java
  src/server/room-service/src/main/java/com/example/roomservice/controller/RoomController.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/RequestExitDto.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/ResponseDto.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/Room.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/RoomRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/RoomViewer/RoomViewer.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/RoomViewer/RoomViewerRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/User/User.java
  src/server/room-service/src/main/java/com/example/roomservice/service/RoomService.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Room/Room.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/RoomViewer/RoomViewer.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/User/User.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Video/Video.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/ViewdHistory/ViewedHistory.java
  src/server/user-service/src/main/java/com/example/userservice/configure/RedisConfig.java
  src/server/user-service/src/main/java/com/example/userservice/configure/S3Config.java
  src/server/user-service/src/main/java/com/example/userservice/configure/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/configure/security/Jwt.java
  src/server/user-service/src/main/java/com/example/userservice/configure/security/WebSecurity.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/ResponseToken.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/Room.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewer.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/User.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Video/Video.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedHistory.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application-auth.yml
  src/server/video-service/src/main/java/com/example/videoservice/entity/User/User.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Video/Video.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
Labels: feat, fix, refactor

#199 fix : delete lastAt field in User entity
  src/server/main-service/src/main/java/com/example/mainservice/entity/Room/RoomRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/User.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/VideoRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/User/User.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/User/User.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/User/User.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Video/Video.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
Labels: fix

#201 feat : api feature list (main-service, video-service)
  src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewer.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedHistory.java
  src/server/main-service/src/main/java/com/example/mainservice/service/MainService.java
  src/server/upload-service/src/main/resources/application-s3.yml
  src/server/video-service/src/main/java/com/example/videoservice/dto/VideoResponseDto.java
  src/server/video-service/src/main/java/com/example/videoservice/service/VideoService.java
  src/server/video-service/src/main/resources/application.yml
Labels: feat

#203 feat : connect room-service api #192
  data/mariadb/schema.sql
  src/frontend/src/App.jsx
  src/frontend/src/components/feedbacks/Modals/MakeStreamModal/MakeStreamModal.jsx
  src/frontend/src/components/layouts/Header/Dropdowns/AddVideoDropdown.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.style.js
  src/frontend/src/pages/Studio/MobileStudioPage/MobileStudioPage.jsx
  src/frontend/src/pages/Studio/StudioPage/StudioPage.jsx
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/hook/index.js
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useGetVideoInfo.js
  src/frontend/src/utils/hook/query/useMakeLive.js
  src/frontend/src/utils/hook/useMediaSoupConsume.js
  src/frontend/src/utils/hook/useMediaSoupProduce.js
  src/frontend/src/utils/service/index.js
  src/frontend/src/utils/service/time.service.js
  src/server/api-gateway/src/main/java/com/example/apigateway/filter/AuthenticationFilter.java
  src/server/api-gateway/src/main/resources/application.yml
  src/server/main-service/src/main/java/com/example/mainservice/entity/Room/Room.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewer.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/User.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/Video.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedHistory.java
  src/server/room-service/src/main/java/com/example/roomservice/controller/RoomController.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/RequestExitDto.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/ResponseDto.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/Room.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/RoomRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/RoomViewer/RoomViewer.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/RoomViewer/RoomViewerRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/User/User.java
  src/server/room-service/src/main/java/com/example/roomservice/service/RoomService.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Room/Room.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/RoomViewer/RoomViewer.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/User/User.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Video/Video.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/ViewdHistory/ViewedHistory.java
  src/server/user-service/src/main/java/com/example/userservice/configure/RedisConfig.java
  src/server/user-service/src/main/java/com/example/userservice/configure/S3Config.java
  src/server/user-service/src/main/java/com/example/userservice/configure/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/configure/security/Jwt.java
  src/server/user-service/src/main/java/com/example/userservice/configure/security/WebSecurity.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/ResponseToken.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Room/Room.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewer.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/User.java
  src/server/user-service/src/main/java/com/example/userservice/entity/Video/Video.java
  src/server/user-service/src/main/java/com/example/userservice/entity/ViewdHistory/ViewedHistory.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application-auth.yml
  src/server/video-service/src/main/java/com/example/videoservice/entity/User/User.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/Video/Video.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
Labels: feat

#206 feat : connect room-service api
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Info.plist
  src/ios/PlayGround/PlayGround/Network/MainService/MainDataModel.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/request/Request.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/room/RoomClient.swift
  src/ios/PlayGround/PlayGround/Network/RoomServiceAPI/RoomDataModel.swift
  src/ios/PlayGround/PlayGround/Network/RoomServiceAPI/RoomServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Broadcast.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/CreateInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/CreateNavigationController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewModel.swift
Labels: feat, design

#212 feat : add delete room on room-service
  src/server/room-service/src/main/java/com/example/roomservice/controller/RoomController.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/ResponseExitDto.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/Room.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/RoomRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/User/User.java
  src/server/room-service/src/main/java/com/example/roomservice/service/RoomService.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/history/ResponseHistory.java
  src/server/user-service/src/main/java/com/example/userservice/dto/history/ResponseRoom.java
  src/server/user-service/src/main/java/com/example/userservice/entity/RoomViewer/RoomViewer.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
Labels: feat

#205 feat : revised main-service, video-service, data.sql(dummy)
  data/mariadb/data.sql
  src/server/Reame.md
  src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewer.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedHistory.java
  src/server/main-service/src/main/java/com/example/mainservice/service/MainService.java
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
  src/server/video-service/src/main/java/com/example/videoservice/service/VideoService.java
Labels: feat

#214 docs : add README.md and comment
  data/mariadb/schema.sql
  src/server/room-service/README.md
  src/server/room-service/src/main/java/com/example/roomservice/entity/RoomViewer/RoomViewer.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/User/UserRepository.java
  src/server/room-service/src/main/java/com/example/roomservice/service/AmazonS3Service.java
  src/server/room-service/src/main/java/com/example/roomservice/service/RoomService.java
  src/server/user-service/README.md
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/NicknameDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/Pwd.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/PwdDto.java
  src/server/user-service/src/main/java/com/example/userservice/service/AmazonS3Service.java
  src/server/user-service/src/main/java/com/example/userservice/service/HistoryService.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application.yml
Labels: docs

#213 docs, refactor : add Readme.md to services, remove unused file
  src/server/chat-service/Readme.md
  src/server/chat-service/src/main/java/com/example/chatservice/config/RedisConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/config/WebSocketConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/IndexController.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RedisPubSubController.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RoomController.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/ExceptionController.java
  src/server/chat-service/src/main/java/com/example/chatservice/handler/CustomHandshakeHandler.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/ChatProduce.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/room/Room.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/stomp_principal/StompPrincipal.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisPublisher.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisSubscriber.java
  src/server/chat-service/src/main/java/com/example/chatservice/stomp/StompHandler.java
  src/server/chat-service/src/main/java/com/example/chatservice/utils/ClientMessaging.java
  src/server/main-service/Readme.md
  src/server/main-service/src/main/java/com/example/mainservice/configure/BaseConfiguration.java
  src/server/main-service/src/main/java/com/example/mainservice/controller/FriendController.java
  src/server/main-service/src/main/java/com/example/mainservice/controller/MainController.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/HomeListDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/NotificationDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoResponseDto.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/FriendWait/FriendWait.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Metadata/Metadata.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Notification/Notification.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewer.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewerRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/User.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/UserRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/Video.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/VideoRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedHistory.java
  src/server/main-service/src/main/java/com/example/mainservice/exceptionHandler/ExceptionController.java
  src/server/main-service/src/main/java/com/example/mainservice/service/FriendService.java
  src/server/main-service/src/main/java/com/example/mainservice/service/MainService.java
  src/server/status-service/Readme.md
  src/server/upload-service/Readme.md
  src/server/upload-service/src/main/java/com/example/uploadservice/controller/UploadController.java
  src/server/upload-service/src/main/java/com/example/uploadservice/dto/VideoDto.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Metadata/Metadata.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Room/Room.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Room/RoomRepository.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/RoomViewer/RoomViewer.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/Video/Video.java
  src/server/upload-service/src/main/java/com/example/uploadservice/entity/ViewdHistory/ViewedHistory.java
  src/server/video-service/Readme.md
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
  src/server/video-service/src/main/java/com/example/videoservice/exceptionHandler/customexception/CustomVideoException.java
  src/server/video-service/src/main/java/com/example/videoservice/service/VideoService.java
Labels: refactor, docs

#219 docs : add backend codeReview Guide
  src/server/backend_hanui_codereview.txt
  src/server/backend_woojae_codereview.pdf
Labels: docs

#221 docs : update code review file
  src/server/backend_hanui_codereview.txt
Labels: docs

#220 feat, fix, refactor : create status-server
  src/server/status-service/.gitignore
  src/server/status-service/HELP.md
  src/server/status-service/build.gradle
  src/server/status-service/gradle/wrapper/gradle-wrapper.jar
  src/server/status-service/gradle/wrapper/gradle-wrapper.properties
  src/server/status-service/gradlew
  src/server/status-service/gradlew.bat
  src/server/status-service/settings.gradle
  src/server/status-service/src/main/java/com/example/statusservice/StatusServerApplication.java
  src/server/status-service/src/main/java/com/example/statusservice/config/RedisConfig.java
  src/server/status-service/src/main/java/com/example/statusservice/config/WebSocketConfig.java
  src/server/status-service/src/main/java/com/example/statusservice/controller/IndexController.java
  src/server/status-service/src/main/java/com/example/statusservice/controller/RedisPubSubController.java
  src/server/status-service/src/main/java/com/example/statusservice/dto/UserDto.java
  src/server/status-service/src/main/java/com/example/statusservice/entity/User/User.java
  src/server/status-service/src/main/java/com/example/statusservice/entity/User/UserRepository.java
  src/server/status-service/src/main/java/com/example/statusservice/entity/User/UserState.java
  src/server/status-service/src/main/java/com/example/statusservice/exception/CustomStatusException.java
  src/server/status-service/src/main/java/com/example/statusservice/exception/ErrorCode.java
  src/server/status-service/src/main/java/com/example/statusservice/exception/ErrorResponse.java
  src/server/status-service/src/main/java/com/example/statusservice/exception/ExceptionController.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisSubscriber.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisUserService.java
  src/server/status-service/src/main/java/com/example/statusservice/stomp/StompHandler.java
  src/server/status-service/src/main/java/com/example/statusservice/utils/ClientMessaging.java
  src/server/status-service/src/main/java/com/example/statusservice/utils/RedisMessaging.java
  src/server/status-service/src/main/resources/application.yml
  src/server/status-service/src/main/resources/templates/footer.mustache
  src/server/status-service/src/main/resources/templates/header.mustache
  src/server/status-service/src/main/resources/templates/home.mustache
  src/server/status-service/src/test/java/com/example/statusserver/StatusServerApplicationTests.java
Labels: feat, fix

#222 feat : connect video/audio consume
  src/ios/PlayGround/PlayGround/Network/Mediasoup/request/Request.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/room/RoomClient.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/socket/EchoSocket.swift
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/Tab.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: feat

#229 fix : fix audio output issue
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Info.plist
  src/ios/PlayGround/PlayGround/Network/Mediasoup/request/Request.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/room/RoomClient.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/SFSafariViewController+shared.swift
  src/ios/PlayGround/PlayGround/Presentation/SceneDelegate.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: fix

#231 fix : add video pk (video-service)
  src/server/video-service/src/main/java/com/example/videoservice/dto/VideoResponseDto.java
Labels: fix

#232 feat : chat-service, status-service
  config/docker-compose.yml
  src/server/chat-service/build.gradle
  src/server/chat-service/src/main/java/com/example/chatservice/config/CorsConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/config/RedisConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/IndexController.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RedisPubSubController.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RoomController.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/chat/ChatConsume.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/chat/ChatProduce.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/chat/ChatType.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/chat/EnterConsume.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/chat/SenderRole.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/room/Room.java
  src/server/chat-service/src/main/java/com/example/chatservice/entity/User.java
  src/server/chat-service/src/main/java/com/example/chatservice/entity/UserRepository.java
  src/server/chat-service/src/main/java/com/example/chatservice/entity/UserState.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/CustomChatException.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/ErrorCode.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/ExceptionController.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/room/Room.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/JwtService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisSubscriber.java
  src/server/chat-service/src/main/java/com/example/chatservice/stomp/StompHandler.java
  src/server/chat-service/src/main/java/com/example/chatservice/utils/RedisMessaging.java
  src/server/chat-service/src/main/resources/application.yml
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
  src/server/status-service/Dockerfile
  src/server/status-service/build.gradle
  src/server/status-service/src/main/java/com/example/statusservice/config/CorsConfig.java
  src/server/status-service/src/main/java/com/example/statusservice/dto/UserDto.java
  src/server/status-service/src/main/java/com/example/statusservice/exception/CustomStatusException.java
  src/server/status-service/src/main/java/com/example/statusservice/exception/ErrorCode.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/JwtService.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisUserService.java
  src/server/status-service/src/main/java/com/example/statusservice/stomp/StompHandler.java
  src/server/status-service/src/main/resources/application.yml
  src/server/status-service/src/main/resources/templates/home.mustache
  src/server/status-service/src/test/java/com/example/statusserver/StatusServerApplicationTests.java
  src/server/upload-service/src/main/java/com/example/uploadservice/service/VideoService.java
Labels: feat

#238 feat : add uploaderUuid at /list api (main-service)
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoResponseDto.java
Labels: feat

#236 feat : connect with status-service
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Network/MainService/MainDataModel.swift
  src/ios/PlayGround/PlayGround/Network/StatusService/StatusDataModel.swift
  src/ios/PlayGround/PlayGround/Network/StatusService/StatusServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/VideoService/VideoDataModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/HomeTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MyTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/StatusManager.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/Friend.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendPopUpViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/TransitionDelegate.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/ViewModel/FriendViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyHistoryViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPage.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPageViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/HorizontalVideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/MyPageViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/RecentViewedCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/VideoListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayExplainViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/Podfile
  src/ios/PlayGround/Podfile.lock
Labels: feat

#241 fix : add lastViewedAt (video-service)
  src/server/video-service/src/main/java/com/example/videoservice/entity/ViewdHistory/ViewedHistory.java
  src/server/video-service/src/main/java/com/example/videoservice/service/VideoService.java
Labels: fix

#244 feat : connect with status-service
  src/frontend/src/components/layouts/Header/Dropdowns/ProfileDropdown.jsx
  src/frontend/src/components/layouts/SideFriendList/FriendItem.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.jsx
  src/frontend/src/components/layouts/SideNavigation/SideNavigation.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.jsx
  src/frontend/src/pages/Channel/ChannelMetaData/ChannelMetaData.jsx
  src/frontend/src/pages/Channel/ChannelPage/ChannelPage.jsx
  src/frontend/src/pages/Home/HomePage/HomePage.jsx
  src/frontend/src/pages/My/MyPage/MyPage.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/hook/index.js
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useGetChanneInfo.js
  src/frontend/src/utils/hook/query/useGetFriendStatus.js
  src/frontend/src/utils/hook/query/useGetMyList.js
  src/frontend/src/utils/hook/query/useReqFriend.js
  src/frontend/src/utils/hook/useStatusSocket.js
  src/frontend/src/utils/service/time.service.js
Labels: feat

#246 feat : connect with user-service MyPage
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Network/ErrorCodeConverter.swift
  src/ios/PlayGround/PlayGround/Network/MainService/MainDataModel.swift
  src/ios/PlayGround/PlayGround/Network/MainService/MainServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/RoomServiceAPI/RoomServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserDataModel.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/VideoService/VideoDataModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/HomeTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MyTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UIImageView+downloadImageFrom.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/FriendPopUpViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Search/SearchViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyHistoryViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPageViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/HorizontalVideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/RecentViewedCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/VideoListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/Channel.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ChannelViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ChannelViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayExplainViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: feat

#249 feat : connect with chat-service
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatDataModel.swift
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/RoomServiceAPI/RoomServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/Create.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/Live.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/LiveChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/Chat.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChatViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewModel.swift
Labels: feat

#247 feat : update friend list MariaDB to Redis (main-service)
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RoomController.java
  src/server/chat-service/src/main/java/com/example/chatservice/dto/room/RoomResponseDto.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/main-service/Dockerfile
  src/server/main-service/src/main/java/com/example/mainservice/dto/PartnerDto.java
  src/server/main-service/src/main/java/com/example/mainservice/service/FriendService.java
  src/server/main-service/src/main/java/com/example/mainservice/utils/HttpRequest.java
  src/server/main-service/src/main/resources/application.yml
  src/server/status-service/src/main/java/com/example/statusservice/controller/IndexController.java
  src/server/status-service/src/main/java/com/example/statusservice/controller/UserController.java
  src/server/status-service/src/main/java/com/example/statusservice/dto/FriendDto.java
  src/server/status-service/src/main/java/com/example/statusservice/dto/PartnerDto.java
  src/server/status-service/src/main/java/com/example/statusservice/dto/UserDto.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisUserService.java
  src/server/upload-service/gradle/wrapper/gradle-wrapper.properties
  src/server/upload-service/gradlew
  src/server/upload-service/src/main/java/com/example/uploadservice/service/VideoService.java
  src/server/upload-service/src/main/java/com/example/uploadservice/utils/HttpRequest.java
  src/server/upload-service/src/main/resources/application.yml
Labels: feat, fix

#251 fix : improve register process
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/NickNameInputViewController.swift
Labels: fix

#250 feat : connect with status-service
  src/frontend/src/components/chats/ChatRoom/ChatRoom.jsx
  src/frontend/src/components/chats/ChatRoom/ChatRoom.style.js
  src/frontend/src/components/dataDisplays/ChatDialog/ChatDialog.jsx
  src/frontend/src/components/dataDisplays/ChatDialog/ChatDialog.style.js
  src/frontend/src/components/feedbacks/Modals/AdviseModal.jsx
  src/frontend/src/components/feedbacks/Modals/MakeStreamModal/MakeStreamModal.jsx
  src/frontend/src/components/feedbacks/Modals/Modal.style.js
  src/frontend/src/pages/Studio/MobileStudioPage/MobileStudioPage.jsx
  src/frontend/src/pages/Studio/MobileStudioPage/MobileStudioPage.style.js
  src/frontend/src/pages/Studio/StreamStatusBar/StreamStatusBar.jsx
  src/frontend/src/pages/Studio/StudioPage/StudioPage.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/context/index.js
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useGetChatRoomInfo.js
  src/frontend/src/utils/hook/useMediaSoupConsume.js
  src/frontend/src/utils/hook/useMediaSoupProduce.js
  src/frontend/src/utils/hook/useSocket.js
  src/frontend/src/utils/service/time.service.js
Labels: feat

#253 chore : group view, controller, and viewModel with folders
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/View/Create.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/ViewController/CreateInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/ViewController/CreateNavigationController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/ViewController/CreatePopOverViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/View/CameraView.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/View/Live.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/View/LiveChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/ViewController/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/View/Upload.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Upload/ViewController/UploadViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/View/Tab.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/ViewController/CustomTabViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/SFSafariViewController+shared.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/View/Friend.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/View/FriendListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/ViewController/FriendListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/ViewController/FriendPopUpViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/CategoryCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/Home.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewController/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewController/HomeNavigationController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/View/FriendRequestCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/View/Notice.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/View/NoticeCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/ViewController/FriendRequestViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/ViewController/NoticeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/ViewModel/NoticeViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Search/View/Search.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Search/ViewController/SearchViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/View/Base.lproj/Login.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Login/ViewController/LoginNavigationController.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/ViewController/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/View/HorizontalVideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/View/MyPage.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/View/RecentViewedCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewModel/AccountInfoViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewModel/MyHistoryViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewModel/MyPageViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/View/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/View/Channel.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ViewController/ChannelViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ViewModel/ChannelViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/View/Chat.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/View/ChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ViewController/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ViewModel/ChatViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/View/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/View/Player.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewController/PlayExplainViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewController/PlayViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewModel/PlayViewModel.swift
Labels: chore

#254 feat : media-soup close logic
  config/docker-compose.yml
  src/frontend/src/pages/Studio/MobileStudioPage/MobileStudioPage.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
Labels: feat

#258 feat : FriendStatus SideNavBar online circle
  src/frontend/src/components/layouts/Header/Dropdowns/AlarmDropdown.jsx
  src/frontend/src/components/layouts/Header/Dropdowns/Dropdown.style.js
  src/frontend/src/components/layouts/SideFriendList/FriendItem.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.style.js
Labels: feat, design

#255 feat : connect room-servie and mediasoup
  src/ios/PlayGround/PlayGround/Network/Mediasoup/socket/EchoSocket.swift
  src/ios/PlayGround/PlayGround/Presentation/SceneDelegate.swift
Labels: feat

#257 feat : add topic of update friend list (status-service)
  src/server/main-service/src/main/java/com/example/mainservice/service/FriendService.java
  src/server/main-service/src/main/java/com/example/mainservice/utils/HttpRequest.java
  src/server/status-service/src/main/java/com/example/statusservice/controller/UserController.java
  src/server/status-service/src/main/java/com/example/statusservice/dto/UserDto.java
  src/server/status-service/src/main/java/com/example/statusservice/exceptionhandler/customexception/ErrorCode.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisSubscriber.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisUserService.java
  src/server/status-service/src/main/resources/templates/home.mustache
Labels: feat

#261 docs : updated code review txt
  src/server/backend_hanui_codereview.txt
Labels: docs

#262 feat : add friend management logic
  src/frontend/src/components/layouts/Header/Dropdowns/AlarmDropdown.jsx
  src/frontend/src/pages/Channel/ChannelMetaData/ChannelMetaData.jsx
  src/frontend/src/pages/Studio/StudioPage/StudioPage.jsx
  src/frontend/src/pages/VideoPlay/VideoPlayPage/VideoPlayPage.jsx
  src/frontend/src/utils/hook/query/useHandleFriendReq.js
  src/frontend/src/utils/hook/useMediaSoupProduce.js
  src/frontend/src/utils/hook/useStatusSocket.js
  src/frontend/src/utils/hook/useStreamMedia.js
Labels: feat

#264 feat : add friend management logic
  src/ios/PlayGround/PlayGround/Network/NetworkResultManager.swift
  src/ios/PlayGround/PlayGround/Network/StatusService/StatusDataModel.swift
  src/ios/PlayGround/PlayGround/Network/StatusService/StatusServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/StatusManager.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountEditViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ViewController/ChannelViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/View/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewController/PlayViewController.swift
Labels: feat

#266 docs : add yml file
  src/server/backend_hanui_codereview.txt
  src/server/chat-service/Readme.md
  src/server/main-service/Readme.md
  src/server/status-service/Readme.md
  src/server/upload-service/Readme.md
Labels: docs

#267 docs : add yml file
  src/server/backend_hanui_codereview.txt
Labels: docs

#270 feat : init data of redis
  config/docker-compose.yml
  data/redis/Dockerfile
  data/redis/my-data.redis
  data/redis/my-redis.sh
Labels: feat

#273 design : add loading images and icon in project
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  src/ios/PlayGround/PlayGround/Network/MainService/LoadingView.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/View/Create.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/ViewController/CreateInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/PgLoading.json
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/Home.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewController/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/ViewController/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/IdInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/NickNameInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/PwInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/View/Channel.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ViewController/ChannelViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ViewModel/ChannelViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewController/PlayViewController.swift
  src/ios/PlayGround/Podfile
  src/ios/PlayGround/Podfile.lock
Labels: design

#276 fix : send email api on user-service
  src/server/user-service/build.gradle
  src/server/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/user/Email.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application-auth.yml
  src/server/user-service/src/main/resources/application.yml
Labels: fix

#274 feat : updated error code
  config/docker-compose.yml
  resources/error-code.json
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/status-service/src/main/java/com/example/statusservice/controller/UserController.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisUserService.java
  src/server/status-service/src/main/java/com/example/statusservice/stomp/StompHandler.java
  src/server/status-service/src/main/resources/templates/home.mustache
Labels: feat

#279 remove eureka server
  src/infra/api-gateway/src/main/resources/application.yml
  src/infra/service-discovery/.gitignore
  src/infra/service-discovery/build.gradle
  src/infra/service-discovery/gradle/wrapper/gradle-wrapper.jar
  src/infra/service-discovery/gradle/wrapper/gradle-wrapper.properties
  src/infra/service-discovery/gradlew
  src/infra/service-discovery/gradlew.bat
  src/infra/service-discovery/settings.gradle
  src/infra/service-discovery/src/main/java/com/example/servicediscovery/ServiceDiscoveryApplication.java
  src/infra/service-discovery/src/main/resources/application.yml
  src/infra/service-discovery/src/test/java/com/example/servicediscovery/ServiceDiscoveryApplicationTests.java
Labels: remove

#286 fix : error handling (chat-service, status-service)
  src/server/chat-service/src/main/java/com/example/chatservice/config/WebSocketConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RedisPubSubController.java
  src/server/chat-service/src/main/java/com/example/chatservice/exceptionhandler/ExceptionController.java
  src/server/chat-service/src/main/java/com/example/chatservice/exceptionhandler/customexception/CustomChatException.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/JwtService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/chat-service/src/main/java/com/example/chatservice/stomp/StompHandler.java
  src/server/status-service/src/main/java/com/example/statusservice/config/WebSocketConfig.java
  src/server/status-service/src/main/java/com/example/statusservice/controller/UserController.java
  src/server/status-service/src/main/java/com/example/statusservice/exceptionhandler/ExceptionController.java
  src/server/status-service/src/main/java/com/example/statusservice/exceptionhandler/customexception/CustomStatusException.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/JwtService.java
  src/server/status-service/src/main/java/com/example/statusservice/redis/RedisUserService.java
Labels: fix

#289 feat : add error handling while socket connection
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create/View/Create.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/View/LiveChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/ViewController/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/StatusManager.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewController/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ViewController/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ViewModel/ChatViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/View/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewController/PlayExplainViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/ViewController/PlayViewController.swift
  src/ios/PlayGround/Pods/Target Support Files/Pods-PlayGround/Pods-PlayGround-frameworks.sh
Labels: feat

#288 feat : add mediasoup function(load balancing, scalability)
  src/server/mediasoup/package.json
  src/server/mediasoup/server/Room.js
  src/server/mediasoup/server/app.js
  src/server/room-service/build.gradle
  src/server/room-service/src/main/java/com/example/roomservice/RoomServiceApplication.java
  src/server/room-service/src/main/java/com/example/roomservice/controller/RoomController.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/RequestUpdate.java
  src/server/room-service/src/main/java/com/example/roomservice/dto/ResponseUpdate.java
  src/server/room-service/src/main/java/com/example/roomservice/entity/Room/Room.java
  src/server/room-service/src/main/java/com/example/roomservice/exceptionhandler/ErrorResponse.java
  src/server/room-service/src/main/java/com/example/roomservice/exceptionhandler/ExceptionController.java
  src/server/room-service/src/main/java/com/example/roomservice/exceptionhandler/customexception/CustomRoomException.java
  src/server/room-service/src/main/java/com/example/roomservice/exceptionhandler/customexception/ErrorCode.java
  src/server/room-service/src/main/java/com/example/roomservice/service/AmazonS3Service.java
  src/server/room-service/src/main/java/com/example/roomservice/service/RoomService.java
  src/server/room-service/src/main/resources/application.yml
  src/server/user-service/src/main/resources/application.yml
Labels: feat

#291 refactor : improve status disconnection
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/MainService/MainDataModel.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/request/Request.swift
  src/ios/PlayGround/PlayGround/Network/Mediasoup/socket/ActionEvent.swift
  src/ios/PlayGround/PlayGround/Network/NetworkResultManager.swift
  src/ios/PlayGround/PlayGround/Network/StatusService/StatusServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/View/LiveChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Live/ViewController/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/ViewController/CustomTabViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/AccountEditCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/Coordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/CreateTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/HomeTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/MyTabCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/StatusManager.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/View/FriendListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Friend/ViewController/FriendListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/View/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/ViewController/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/View/FriendRequestCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/View/NoticeCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Search/ViewController/SearchViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/View/Base.lproj/Login.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/View/HorizontalVideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/View/RecentViewedCell.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/MyPageViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/VideoListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewModel/MyHistoryViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/SceneDelegate.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ViewController/ChannelViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/View/ChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ViewController/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ViewModel/ChatViewModel.swift
Labels: refactor

#292 docs : add trouble shooting docs
  docs/LeeJaeyun_trouble_shooting.md
Labels: docs

#296 docs : LeeWooJae_trouble_shooting.md
  docs/LeeWooJae_trouble_shooting.md
Labels: docs

#297 docs : add iOS trouble shooting file
  docs/SeoChaehui_trouble_shooting.md
Labels: docs
