Repository StreamingGate/Playground, pull requests merged in 2022-01, with the labels that each got.

#7 chore : compose frontend environment
  .gitignore
  docs/WebRTC.md
  src/frontend/.eslintrc.js
  src/frontend/.storybook/main.js
  src/frontend/.storybook/preview.js
  src/frontend/index.html
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/prettier.config.js
  src/frontend/src/App.jsx
  src/frontend/src/index.jsx
  src/frontend/webpack.config.js
  src/server/.gitkeep
Labels: chore

#15 design : add input and button component
  .github/workflows/chromatic.yml
  src/frontend/.storybook/main.js
  src/frontend/.storybook/preview.js
  src/frontend/src/assets/.gitkeep
  src/frontend/src/assets/font/Roboto-Regular.ttf
  src/frontend/src/components/buttons/Button/Button.jsx
  src/frontend/src/components/buttons/Button/Button.stories.jsx
  src/frontend/src/components/buttons/Button/Button.style.js
  src/frontend/src/components/buttons/index.js
  src/frontend/src/components/core/Typography/Typography.jsx
  src/frontend/src/components/core/Typography/Typography.stories.jsx
  src/frontend/src/components/core/Typography/Typography.style.js
  src/frontend/src/components/core/index.js
  src/frontend/src/components/forms/Input/Input.jsx
  src/frontend/src/components/forms/Input/Input.stories.jsx
  src/frontend/src/components/forms/Input/Input.styles.js
  src/frontend/src/components/forms/button/Button.jsx
  src/frontend/src/components/forms/button/Button.stories.jsx
  src/frontend/src/components/forms/index.js
  src/frontend/src/components/styles/GlobalStyle.jsx
  src/frontend/src/components/styles/NormalizeStyle.jsx
  src/frontend/src/components/styles/index.js
  src/frontend/src/storybookDocs/color.stories.mdx
  src/frontend/src/utils/.gitkeep
  src/frontend/src/utils/constant/index.js
  src/frontend/src/utils/constant/theme.constants.js
  src/frontend/webpack.config.js
Labels: design

#13 chore : add github CI for server
  .github/workflows/chromatic.yml
  .github/workflows/gradle.yml
  docs/WebRTC.md
  src/server/.gitkeep
Labels: chore

#21 chore,feat : add gateway, service discovery, user authentication api
  src/server/api-gateway/.gitignore
  src/server/api-gateway/build.gradle
  src/server/api-gateway/gradle/wrapper/gradle-wrapper.jar
  src/server/api-gateway/gradle/wrapper/gradle-wrapper.properties
  src/server/api-gateway/gradlew
  src/server/api-gateway/gradlew.bat
  src/server/api-gateway/settings.gradle
  src/server/api-gateway/src/main/java/com/example/apigateway/ApiGatewayApplication.java
  src/server/api-gateway/src/main/java/com/example/apigateway/filter/AuthenticationFilter.java
  src/server/api-gateway/src/main/resources/application.yml
  src/server/api-gateway/src/test/java/com/example/apigateway/ApiGatewayApplicationTests.java
  src/server/service-discovery/.gitignore
  src/server/service-discovery/build.gradle
  src/server/service-discovery/gradle/wrapper/gradle-wrapper.jar
  src/server/service-discovery/gradle/wrapper/gradle-wrapper.properties
  src/server/service-discovery/gradlew
  src/server/service-discovery/gradlew.bat
  src/server/service-discovery/settings.gradle
  src/server/service-discovery/src/main/java/com/example/servicediscovery/ServiceDiscoveryApplication.java
  src/server/service-discovery/src/main/resources/application.yml
  src/server/service-discovery/src/test/java/com/example/servicediscovery/ServiceDiscoveryApplicationTests.java
  src/server/user-service/.gitignore
  src/server/user-service/build.gradle
  src/server/user-service/gradle/wrapper/gradle-wrapper.jar
  src/server/user-service/gradle/wrapper/gradle-wrapper.properties
  src/server/user-service/gradlew
  src/server/user-service/gradlew.bat
  src/server/user-service/settings.gradle
  src/server/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserEntity.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserState.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/ErrorResponse.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/ExceptionController.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/CustomUserException.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user-service/src/main/java/com/example/userservice/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  src/server/user-service/src/main/java/com/example/userservice/vo/RequestLogin.java
  src/server/user-service/src/main/java/com/example/userservice/vo/RequestUser.java
  src/server/user-service/src/main/java/com/example/userservice/vo/ResponseLogin.java
  src/server/user-service/src/main/java/com/example/userservice/vo/ResponseUser.java
  src/server/user-service/src/main/resources/application.yml
  src/server/user-service/src/test/java/com/example/userservice/UserServiceApplicationTests.java
Labels: feat, chore

#23 refactor : improve iOS App UX
  src/ios/SG_YouTube/SG_YouTube.xcodeproj/project.pbxproj
  src/ios/SG_YouTube/SG_YouTube/AppUtility.swift
  src/ios/SG_YouTube/SG_YouTube/Base.lproj/Main.storyboard
  src/ios/SG_YouTube/SG_YouTube/Channel/ChannelViewController.swift
  src/ios/SG_YouTube/SG_YouTube/Chat/Chat.storyboard
  src/ios/SG_YouTube/SG_YouTube/Create/Create.storyboard
  src/ios/SG_YouTube/SG_YouTube/Create/CreateNavigationController.swift
  src/ios/SG_YouTube/SG_YouTube/Create/CreatePopOverViewController.swift
  src/ios/SG_YouTube/SG_YouTube/Create/LiveStreamingInfoViewController.swift
  src/ios/SG_YouTube/SG_YouTube/Extensions/UITabBarController+Visibility.swift
  src/ios/SG_YouTube/SG_YouTube/HomeList/Home.storyboard
  src/ios/SG_YouTube/SG_YouTube/HomeList/HomeListViewController.swift
  src/ios/SG_YouTube/SG_YouTube/MyPage/ViewControllers/MyPageViewController.swift
  src/ios/SG_YouTube/SG_YouTube/MyPage/ViewControllers/VideoListViewController.swift
  src/ios/SG_YouTube/SG_YouTube/Play/Play.storyboard
  src/ios/SG_YouTube/SG_YouTube/Play/PlayViewController.swift
  src/ios/SG_YouTube/SG_YouTube/TabBarController.swift
Labels: refactor

#27 feat : fix auth filter at gateway, refactoring user-service
  src/server/api-gateway/src/main/resources/application.yml
  src/server/user-service/build.gradle
  src/server/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserEntity.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserState.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/ErrorResponse.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/ExceptionController.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/CustomUserException.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user-service/src/main/java/com/example/userservice/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  src/server/user-service/src/main/java/com/example/userservice/vo/RequestUser.java
  src/server/user-service/src/main/resources/application.yml
Labels: feat, fix, refactor

#34 refactor : rename package, change service structure
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user_service/.gitignore
  src/server/user_service/build.gradle
  src/server/user_service/gradle/wrapper/gradle-wrapper.jar
  src/server/user_service/gradle/wrapper/gradle-wrapper.properties
  src/server/user_service/gradlew
  src/server/user_service/gradlew.bat
  src/server/user_service/settings.gradle
  src/server/user_service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user_service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user_service/src/main/java/com/example/userservice/dto/RegisterUser.java
  src/server/user_service/src/main/java/com/example/userservice/dto/RequestLogin.java
  src/server/user_service/src/main/java/com/example/userservice/dto/ResponseLogin.java
  src/server/user_service/src/main/java/com/example/userservice/dto/ResponseUser.java
  src/server/user_service/src/main/java/com/example/userservice/dto/UserDto.java
  src/server/user_service/src/main/java/com/example/userservice/entity/User/UserEntity.java
  src/server/user_service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user_service/src/main/java/com/example/userservice/entity/User/UserState.java
  src/server/user_service/src/main/java/com/example/userservice/exceptionhandler/ErrorResponse.java
  src/server/user_service/src/main/java/com/example/userservice/exceptionhandler/ExceptionController.java
  src/server/user_service/src/main/java/com/example/userservice/exceptionhandler/customexception/CustomUserException.java
  src/server/user_service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user_service/src/main/java/com/example/userservice/security/AuthenticationFilter.java
  src/server/user_service/src/main/java/com/example/userservice/security/WebSecurity.java
  src/server/user_service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user_service/src/main/resources/application.yml
  src/server/user_service/src/test/java/com/example/userservice/UserServiceApplicationTests.java
Labels: refactor, rename

#36 design : Home page UI markup
  src/frontend/.eslintrc.js
  src/frontend/.storybook/preview.js
  src/frontend/src/App.jsx
  src/frontend/src/assets/icons/MyVideo.svg
  src/frontend/src/assets/icons/RealTimeMark.svg
  src/frontend/src/assets/image/ThumbNailDummy.jpg
  src/frontend/src/components/buttons/Button/Button.stories.jsx
  src/frontend/src/components/cores/Icons/RealTimeMark.jsx
  src/frontend/src/components/cores/index.js
  src/frontend/src/components/dataDisplays/Avatar/Avatar.stories.jsx
  src/frontend/src/components/feedbacks/BackDrop/BackDrop.jsx
  src/frontend/src/components/feedbacks/BackDrop/BackDrop.stories.jsx
  src/frontend/src/components/feedbacks/BackDrop/BackDrop.style.js
  src/frontend/src/components/forms/Input/Input.stories.jsx
  src/frontend/src/components/forms/Input/Input.styles.js
  src/frontend/src/components/layouts/Header/BaseHeader.jsx
  src/frontend/src/components/layouts/Header/Header.stories.jsx
  src/frontend/src/components/layouts/Header/Header.style.js
  src/frontend/src/components/layouts/Header/SearchForm.jsx
  src/frontend/src/components/layouts/MainLayout/MainLayout.jsx
  src/frontend/src/components/layouts/MainLayout/MainLayout.stories.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.stories.jsx
  src/frontend/src/components/layouts/SideFriendList/SideFriendList.style.js
  src/frontend/src/components/layouts/SideNavigation/SideNavigation.jsx
  src/frontend/src/components/layouts/SideNavigation/SideNavigation.stories.jsx
  src/frontend/src/components/layouts/SideNavigation/SideNavigation.style.js
  src/frontend/src/components/storybook/NormalWrapper.jsx
  src/frontend/src/components/storybook/index.js
  src/frontend/src/components/styles/GlobalStyle.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.stories.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.style.js
  src/frontend/src/components/videos/index.js
  src/frontend/src/pages/Home/HomePage/HomePage.jsx
  src/frontend/src/pages/Home/HomePage/HomePage.stories.jsx
  src/frontend/src/pages/Home/HomePage/HomePage.sytle.js
  src/frontend/src/pages/Home/index.js
  src/frontend/src/utils/constant/breakpoint.constant.js
Labels: design

#43 docs : add mariadb schema ddl
  data/schema.sql
Labels: docs

#45 design : modify register pages ui
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Info.plist
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UIView+takeScreenshot.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/IdInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/NickNameInputViewController.swift
Labels: design

#51 chore : docker-compose.yml (mariadb auto schema create)
  config/docker-compose.yml
  data/mariadb/schema.sql
Labels: chore

#52 refactor : refactor user-service
  .idea/StreamingGate.iml
  src/server/user-service/.gitignore
  src/server/user-service/build.gradle
  src/server/user-service/gradle/wrapper/gradle-wrapper.jar
  src/server/user-service/gradle/wrapper/gradle-wrapper.properties
  src/server/user-service/gradlew
  src/server/user-service/gradlew.bat
  src/server/user-service/settings.gradle
  src/server/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user-service/src/main/java/com/example/userservice/config/RedisConfig.java
  src/server/user-service/src/main/java/com/example/userservice/config/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/config/security/WebSecurity.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/RegisterUser.java
  src/server/user-service/src/main/java/com/example/userservice/dto/RequestLogin.java
  src/server/user-service/src/main/java/com/example/userservice/dto/ResponseLogin.java
  src/server/user-service/src/main/java/com/example/userservice/dto/ResponseUser.java
  src/server/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserEntity.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserState.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/ErrorResponse.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/ExceptionController.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/CustomUserException.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application.yml
  src/server/user-service/src/test/java/com/example/userservice/UserServiceApplicationTests.java
Labels: refactor, rename

#53 design : Channel Page UI markup
  src/frontend/package-lock.json
  src/frontend/src/App.jsx
  src/frontend/src/components/buttons/Button/Button.jsx
  src/frontend/src/components/buttons/Button/Button.stories.jsx
  src/frontend/src/components/buttons/Button/Button.style.js
  src/frontend/src/components/dataDisplays/Avatar/Avatar.jsx
  src/frontend/src/components/dataDisplays/Avatar/Avatar.styles.js
  src/frontend/src/components/dataDisplays/ChatDialog/ChatDialog.jsx
  src/frontend/src/components/layouts/MainLayout/MainLayout.style.js
  src/frontend/src/components/layouts/SideFriendList/FriendItem.jsx
  src/frontend/src/components/layouts/VideoGrid/VideoGrid.jsx
  src/frontend/src/components/layouts/index.js
  src/frontend/src/components/videos/VideoOverview/VideoOverview.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.style.js
  src/frontend/src/pages/Channel/ChannelMetaData/ChannelMetaData.jsx
  src/frontend/src/pages/Channel/ChannelMetaData/ChannelMetaData.style.js
  src/frontend/src/pages/Channel/ChannelPage/ChannelPage.jsx
  src/frontend/src/pages/Channel/ChannelPage/ChannelPage.stories.jsx
  src/frontend/src/pages/Channel/ChannelPage/ChannelPage.style.js
  src/frontend/src/pages/Channel/index.js
  src/frontend/src/pages/Home/HomePage/HomePage.sytle.js
  src/frontend/src/pages/Login/LoginForm/LoginForm.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
  src/frontend/src/utils/constant/breakpoint.constant.js
Labels: design

#58 Develop frontend UI
  src/frontend/.storybook/preview.js
  src/frontend/src/App.jsx
  src/frontend/src/components/layouts/MainLayout/MainLayout.stories.jsx
  src/frontend/src/components/layouts/SideNavigation/SideNavigation.stories.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.jsx
  src/frontend/src/components/videos/VideoOverview/VideoOverview.style.js
  src/frontend/src/pages/Login/LoginPage/LoginPage.stories.jsx
  src/frontend/src/pages/My/MyPage/MyPage.jsx
  src/frontend/src/pages/My/MyPage/MyPage.stories.jsx
  src/frontend/src/pages/My/MyPage/MyPage.style.js
  src/frontend/src/pages/My/index.js
Labels: design

#56 fix : update docker-compose, mariadb schema
  config/docker-compose.yml
  data/mariadb/schema.sql
  src/server/user-service/.gitignore
  src/server/user-service/build.gradle
  src/server/user-service/src/main/java/com/example/userservice/config/security/WebSecurity.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application-auth.yml
  src/server/user-service/src/main/resources/application.yml
Labels: fix

#57 feat : connect HLS player with sample data
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_black.imageset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_black.imageset/play_black.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_black.imageset/play_black@2.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_black.imageset/play_black@3.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_white.imageset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_white.imageset/play_white.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_white.imageset/play_white@2.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/play_white.imageset/play_white@3.png
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/CustomTabViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/AVPlayer+isPlayer.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/CustomSlider.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/Home.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/VideoListCell.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Search/SearchViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/ChannelViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Player.swift
  src/ios/PlayGround/Podfile
  src/ios/PlayGround/Podfile.lock
Labels: feat

#61 fix, chore : update .gitignore (.idea)
  .gitignore
  .idea/StreamingGate.iml
Labels: fix, chore

#65 design : RegisterPage UI markup
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.jsx
  src/frontend/src/components/buttons/Button/Button.jsx
  src/frontend/src/components/buttons/Button/Button.stories.jsx
  src/frontend/src/components/buttons/Button/Button.style.js
  src/frontend/src/components/dataDisplays/Stepper/Stepper.jsx
  src/frontend/src/components/dataDisplays/Stepper/Stepper.stories.jsx
  src/frontend/src/components/dataDisplays/Stepper/Stepper.style.js
  src/frontend/src/components/dataDisplays/index.js
  src/frontend/src/components/forms/Input/Input.jsx
  src/frontend/src/components/forms/Input/Input.stories.jsx
  src/frontend/src/components/forms/Input/Input.styles.js
  src/frontend/src/pages/Login/LoginForm/LoginForm.jsx
  src/frontend/src/pages/Register/RegisterFormStages/RegisterFormStage1.jsx
  src/frontend/src/pages/Register/RegisterFormStages/RegisterFormStage2.jsx
  src/frontend/src/pages/Register/RegisterFormStages/RegisterFormStage3.jsx
  src/frontend/src/pages/Register/RegisterFormStages/RegisterFormStages.style.js
  src/frontend/src/pages/Register/RegisterPage/RegisterPage.jsx
  src/frontend/src/pages/Register/RegisterPage/RegisterPage.stories.jsx
  src/frontend/src/pages/Register/RegisterPage/RegisterPage.style.js
  src/frontend/src/pages/Register/index.js
  src/frontend/src/services/.gitkeep
  src/frontend/src/storybookDocs/color.stories.mdx
  src/frontend/src/utils/constant/breakpoint.constant.js
  src/frontend/src/utils/constant/theme.constants.js
  src/frontend/src/utils/service/index.js
  src/frontend/src/utils/service/media.service.js
  src/frontend/webpack.config.js
Labels: design

#71 feat : connect register and login process with server
  config/docker-compose.yml
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Assets.xcassets/CustomColor/PGMint.colorset/Contents.json
  src/ios/PlayGround/PlayGround/ErrorCodeConverter.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/KeyChainWrapper+Key.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UIViewController+SimpleAlert.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/RegisterHelper.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/UserManager.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/LoginViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPage.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/ViewControllers/AccountInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/IdInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/NickNameInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/PwInputViewController.swift
  src/ios/PlayGround/PlayGround/UserDataModel.swift
  src/ios/PlayGround/PlayGround/UserServiceAPI.swift
  src/ios/PlayGround/Podfile
  src/ios/PlayGround/Podfile.lock
Labels: feat

#73 fix : update mariadb schema
  data/mariadb/schema.sql
Labels: fix

#75 refactor : improve player regarding readability and memory leak
  src/ios/PlayGround/PlayGround/Presentation/Helper/Coordinator/PlayerCoordinator.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayExplainViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Player.swift
Labels: refactor

#77 feat : connect S3 with user-service, add to uploading profiles api
  config/docker-compose.yml
  src/server/user-service/.gitignore
  src/server/user-service/build.gradle
  src/server/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user-service/src/main/java/com/example/userservice/config/S3Config.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/exceptionhandler/customexception/ErrorCode.java
  src/server/user-service/src/main/java/com/example/userservice/service/AmazonS3Service.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application.yml
Labels: feat

#79 feat : modal control logic
  src/frontend/.eslintrc.js
  src/frontend/src/App.jsx
  src/frontend/src/utils/context/index.js
  src/frontend/src/utils/service/index.js
  src/frontend/src/utils/service/modal.service.jsx
  src/frontend/webpack.config.js
Labels: feat

#80 chore : change minimum iOS version
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Broadcast.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Create.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/CreateInfoViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/CustomTab/Tab.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/Home.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Notice/Notice.storyboard
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Search/Search.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Login/Base.lproj/Login.storyboard
  src/ios/PlayGround/PlayGround/Presentation/MyTab/MyPage.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Channel/Channel.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: chore

#81 fix : revised typo semicolon
  data/mariadb/schema.sql
Labels: fix

#85 fix : add validation check in name textField
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/IdInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/PwInputViewController.swift
Labels: fix

#88 feat : create chat-servivce (broadcast)
  .gitignore
  src/server/chat-service/.gitignore
  src/server/chat-service/Dockerfile
  src/server/chat-service/build.gradle
  src/server/chat-service/docker-compose.yml
  src/server/chat-service/gradle/wrapper/gradle-wrapper.jar
  src/server/chat-service/gradle/wrapper/gradle-wrapper.properties
  src/server/chat-service/gradlew
  src/server/chat-service/gradlew.bat
  src/server/chat-service/settings.gradle
  src/server/chat-service/src/main/java/com/example/chatservice/ChatServiceApplication.java
  src/server/chat-service/src/main/java/com/example/chatservice/config/RedisConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/config/WebSocketConfig.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/IndexController.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RedisPubSubController.java
  src/server/chat-service/src/main/java/com/example/chatservice/controller/RoomController.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/CustomChatException.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/ErrorCode.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/ErrorResponse.java
  src/server/chat-service/src/main/java/com/example/chatservice/exception/ExceptionController.java
  src/server/chat-service/src/main/java/com/example/chatservice/handler/CustomHandshakeHandler.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/Chat.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/ChatType.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/chat/SenderRole.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/room/Room.java
  src/server/chat-service/src/main/java/com/example/chatservice/model/stomp_principal/StompPrincipal.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisPublisher.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisRoomService.java
  src/server/chat-service/src/main/java/com/example/chatservice/redis/RedisSubscriber.java
  src/server/chat-service/src/main/java/com/example/chatservice/stomp/StompHandler.java
  src/server/chat-service/src/main/java/com/example/chatservice/utils/ClientMessaging.java
  src/server/chat-service/src/main/java/com/example/chatservice/utils/RedisMessaging.java
  src/server/chat-service/src/main/resources/application.yml
  src/server/chat-service/src/main/resources/templates/footer.mustache
  src/server/chat-service/src/main/resources/templates/header.mustache
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
  src/server/chat-service/src/test/java/com/example/chatservice/ChatServiceApplicationTests.java
  src/server/chat-service/src/test/java/com/example/chatservice/mongodb/ChatRepositoryTest.java
Labels: feat

#90 chore : add chat-service service, rename mariadb service
  config/docker-compose.yml
Labels: chore

#93 refactor : prevent memory leak of player when list disappeared
  src/ios/PlayGround/PlayGround/Presentation/HomeTab/Home/HomeListViewController.swift
Labels: refactor

#92 feat, chore : update docker-compose, chat-service
  config/docker-compose.yml
  src/server/chat-service/docker-compose.yml
  src/server/chat-service/src/main/java/com/example/chatservice/controller/IndexController.java
  src/server/chat-service/src/main/resources/application.yml
Labels: feat, chore

#87 refactor : edit my info at user-service, add edit pwd api
  config/docker-compose.yml
  data/mariadb/schema.sql
  src/server/api-gateway/build.gradle
  src/server/api-gateway/src/main/resources/application.yml
  src/server/service-discovery/build.gradle
  src/server/user-service/build.gradle
  src/server/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  src/server/user-service/src/main/java/com/example/userservice/config/security/AuthenticationFilter.java
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/dto/EmailDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/NicknameDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/PwdDto.java
  src/server/user-service/src/main/java/com/example/userservice/dto/RequestMyinfo.java
  src/server/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserEntity.java
  src/server/user-service/src/main/java/com/example/userservice/entity/User/UserRepository.java
  src/server/user-service/src/main/java/com/example/userservice/service/AmazonS3Service.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
  src/server/user-service/src/main/resources/application.yml
Labels: feat, refactor

#95 refactor : put image to S3 api
  src/server/user-service/src/main/java/com/example/userservice/controller/UserController.java
  src/server/user-service/src/main/java/com/example/userservice/service/AmazonS3Service.java
  src/server/user-service/src/main/java/com/example/userservice/service/UserService.java
Labels: feat, fix, refactor

#99 fix, chore : add eureka into chat-service, fixed static path
  config/docker-compose.yml
  src/server/api-gateway/build.gradle
  src/server/api-gateway/src/main/resources/application.yml
  src/server/chat-service/build.gradle
  src/server/chat-service/src/main/java/com/example/chatservice/ChatServiceApplication.java
  src/server/chat-service/src/main/resources/application.yml
  src/server/chat-service/src/main/resources/templates/footer.mustache
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
Labels: fix, chore

#97 feat : register page api connect
  src/frontend/.storybook/preview.js
  src/frontend/package.json
  src/frontend/src/components/feedbacks/Modals/AdviseModal.jsx
  src/frontend/src/components/feedbacks/Modals/Modal.stories.jsx
  src/frontend/src/components/feedbacks/Modals/Modal.style.js
  src/frontend/src/components/feedbacks/Modals/index.js
  src/frontend/src/components/forms/Input/Input.jsx
  src/frontend/src/components/forms/Input/Input.styles.js
  src/frontend/src/pages/Login/LoginForm/LoginForm.jsx
  src/frontend/src/pages/Login/LoginForm/LoginForm.style.js
  src/frontend/src/pages/Login/LoginPage/LoginPage.stories.jsx
  src/frontend/src/pages/Register/RegisterFormStages/RegisterFormStage1.jsx
  src/frontend/src/pages/Register/RegisterFormStages/RegisterFormStage2.jsx
  src/frontend/src/pages/Register/RegisterPage/RegisterPage.jsx
  src/frontend/src/pages/Register/RegisterPage/RegisterPage.stories.jsx
  src/frontend/src/utils/constant/validation.constant.js
  src/frontend/src/utils/hook/query/index.js
  src/frontend/src/utils/hook/query/useLogin.js
  src/frontend/src/utils/hook/query/useUserRegister.js
  src/frontend/src/utils/hook/query/useVerifyEmail.js
  src/frontend/src/utils/service/index.js
  src/frontend/src/utils/service/localstorage.service.js
Labels: feat

#100 fix : modify connection with user-service api
  src/ios/PlayGround/PlayGround/ErrorCodeConverter.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/Register.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/IdInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/NickNameInputViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Register/ViewControllers/PwInputViewController.swift
  src/ios/PlayGround/PlayGround/UserServiceAPI.swift
Labels: fix

#102 chore : exclude chat-service from api-gateway
  config/docker-compose.yml
  src/server/api-gateway/src/main/resources/application.yml
  src/server/chat-service/src/main/resources/application.yml
Labels: chore

#104 feat : add basic chat-service
  config/docker-compose.yml
  src/ios/PlayGround/PlayGround.xcodeproj/project.pbxproj
  src/ios/PlayGround/PlayGround/Assets.xcassets/bottomArrow_blueCircle.imageset/Contents.json
  src/ios/PlayGround/PlayGround/Assets.xcassets/bottomArrow_blueCircle.imageset/bottomArrow_blueCircle.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/bottomArrow_blueCircle.imageset/bottomArrow_blueCircle@2.png
  src/ios/PlayGround/PlayGround/Assets.xcassets/bottomArrow_blueCircle.imageset/bottomArrow_blueCircle@3.png
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatDataModel.swift
  src/ios/PlayGround/PlayGround/Network/ChatService/ChatServiceAPI.swift
  src/ios/PlayGround/PlayGround/Network/ErrorCodeConverter.swift
  src/ios/PlayGround/PlayGround/Network/GatewayManager.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserDataModel.swift
  src/ios/PlayGround/PlayGround/Network/UserService/UserServiceAPI.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/DataHelper.swift
  src/ios/PlayGround/PlayGround/Presentation/Helper/Extensions/UITablewView+ScrollToBottom.swift
  src/ios/PlayGround/PlayGround/Presentation/Login/Base.lproj/Login.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/Chat.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChatSendDelegate.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChatViewModel.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
  src/ios/PlayGround/Podfile
  src/ios/PlayGround/Podfile.lock
  src/server/api-gateway/build.gradle
  src/server/api-gateway/src/main/resources/application.yml
  src/server/chat-service/build.gradle
  src/server/chat-service/src/main/java/com/example/chatservice/ChatServiceApplication.java
  src/server/chat-service/src/main/resources/application.yml
  src/server/chat-service/src/main/resources/templates/footer.mustache
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
Labels: feat

#103 feat, chore, : create main-service api, add to api-gateway
  config/docker-compose.yml
  data/mariadb/data.sql
  data/mariadb/schema.sql
  src/server/api-gateway/src/main/resources/application.yml
  src/server/chat-service/build.gradle
  src/server/main-service/.gitignore
  src/server/main-service/Dockerfile
  src/server/main-service/build.gradle
  src/server/main-service/gradle/wrapper/gradle-wrapper.jar
  src/server/main-service/gradle/wrapper/gradle-wrapper.properties
  src/server/main-service/gradlew
  src/server/main-service/gradlew.bat
  src/server/main-service/settings.gradle
  src/server/main-service/src/main/java/com/example/mainservice/MainServiceApplication.java
  src/server/main-service/src/main/java/com/example/mainservice/configure/BaseConfiguration.java
  src/server/main-service/src/main/java/com/example/mainservice/controller/FriendController.java
  src/server/main-service/src/main/java/com/example/mainservice/controller/MainController.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/FriendDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/FriendWaitDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/LiveRoomDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/NotificationDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoActionDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoListDto.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Category.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/FriendWait/FriendWait.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/FriendWait/FriendWaitRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/LiveRoom/LiveRoom.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/LiveRoom/LiveRoomRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/LiveViewer/LiveViewer.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/LiveViewer/LiveViewerRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Metadata/Metadata.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Metadata/MetadataRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Metadata/VideoState.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Notification/NotiType.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Notification/Notification.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Notification/NotificationRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/UserEntity.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/UserRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/User/UserState.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/Video.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Video/VideoRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedHistory.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/ViewdHistory/ViewedRepository.java
  src/server/main-service/src/main/java/com/example/mainservice/exceptionHandler/ErrorResponse.java
  src/server/main-service/src/main/java/com/example/mainservice/exceptionHandler/ExceptionController.java
  src/server/main-service/src/main/java/com/example/mainservice/exceptionHandler/customexception/CustomMainException.java
  src/server/main-service/src/main/java/com/example/mainservice/exceptionHandler/customexception/ErrorCode.java
  src/server/main-service/src/main/java/com/example/mainservice/service/FriendService.java
  src/server/main-service/src/main/java/com/example/mainservice/service/MainService.java
  src/server/main-service/src/main/resources/application.yml
  src/server/main-service/src/main/resources/data.sql
  src/server/main-service/src/test/java/com/example/mainservice/FriendServiceTest.java
  src/server/main-service/src/test/java/com/example/mainservice/MainServiceApplicationTests.java
  src/server/main-service/src/test/java/com/example/mainservice/MainServiceTest.java
Labels: feat, chore

#105 feat, remove : remove data.sql from main-service, set ddl-auto NONE, set double quotes to dummy data
  data/mariadb/data.sql
  src/server/main-service/src/main/java/com/example/mainservice/dto/FriendDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/FriendWaitDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/LiveRoomDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/NotificationDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoActionDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoDto.java
  src/server/main-service/src/main/java/com/example/mainservice/dto/VideoListDto.java
  src/server/main-service/src/main/java/com/example/mainservice/entity/Notification/NotiType.java
  src/server/main-service/src/main/resources/application.yml
  src/server/main-service/src/main/resources/data.sql
Labels: feat, remove

#108 fix : client chat-service connection url
  src/server/chat-service/build.gradle
  src/server/chat-service/src/main/java/com/example/chatservice/ChatServiceApplication.java
  src/server/chat-service/src/main/resources/templates/room.mustache
  src/server/chat-service/src/main/resources/templates/roomdetail.mustache
Labels: fix

#112 feat : connect chat api
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/assets/icons/ScrollDown.svg
  src/frontend/src/components/buttons/Button/Button.jsx
  src/frontend/src/components/buttons/Button/Button.stories.jsx
  src/frontend/src/components/buttons/Button/Button.style.js
  src/frontend/src/components/buttons/IconButton/IconButton.jsx
  src/frontend/src/components/cores/Icons/ScrollDown.jsx
  src/frontend/src/components/cores/index.js
  src/frontend/src/components/dataDisplays/ChatDialog/ChatDialog.jsx
  src/frontend/src/components/forms/Input/Input.jsx
  src/frontend/src/components/forms/Input/Input.styles.js
  src/frontend/src/pages/Register/RegisterPage/RegisterPage.jsx
  src/frontend/src/pages/VideoPlay/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/VideoPlay/ChatRoom/ChatRoom.style.js
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.jsx
  src/frontend/src/pages/VideoPlay/VideoMetaData/VideoMetaData.style.js
  src/frontend/src/utils/hook/index.js
  src/frontend/src/utils/hook/useSocket.js
Labels: feat, design

#111 feat : connect chat-service with broadcasting page
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/Broadcast.storyboard
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/LiveChatCell.swift
  src/ios/PlayGround/PlayGround/Presentation/CreateTab/LiveViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/Chat.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Chat/ChattingViewController.swift
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/Play.storyboard
  src/ios/PlayGround/PlayGround/Presentation/Video/Play/PlayViewController.swift
Labels: feat, design
